// <auto-generated />
using System;
using CrudInCoreWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudInCoreWebApi.Migrations
{
    [DbContext(typeof(CrudInCoreWebApiContext))]
    partial class CrudInCoreWebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudInCoreWebApi.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraineeID");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            TraineeID = 1,
                            Address = "Dhaka",
                            CellPhoneNo = "01813148110",
                            DateOfBirth = new DateTime(1994, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailID = "ali@gmail.com",
                            Gender = "Male",
                            Name = "ALI"
                        },
                        new
                        {
                            TraineeID = 2,
                            Address = "Ctg",
                            CellPhoneNo = "01813148110",
                            DateOfBirth = new DateTime(1994, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailID = "harami@gmail.com",
                            Gender = "Female",
                            Name = "Harami"
                        },
                        new
                        {
                            TraineeID = 3,
                            Address = "Rohingga",
                            CellPhoneNo = "01815501137",
                            DateOfBirth = new DateTime(1994, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailID = "arefin@gmail.com",
                            Gender = "Male",
                            Name = "Arefin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
